name: nl-processors
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - datalad
  - tqdm
  - python
  - matplotlib
  - ipython
  - pip
  - jupyterlab
  - pytorch
  - torchvision
  - pandas
  - numpy
  - scipy
  - pip:
    - natsort
    - nibabel
    - git+https://github.com/PyMVPA/PyMVPA